import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { GoogleAuth } from "npm:google-auth-library";
import { enforceRateLimit, isUuid, readJsonObject, verifyCaller, writeAudit } from "../_shared/auth.ts";

const URL=Deno.env.get("SUPABASE_URL")??"";
const ANON=Deno.env.get("SUPABASE_ANON_KEY")??Deno.env.get("SUPABASE_PUBLISHABLE_KEY")??"";
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??Deno.env.get("SUPABASE_SECRET_KEY")??"";
const PROJECT=Deno.env.get("GOOGLE_CLOUD_PROJECT_ID")??"";
const MAX_CONCURRENCY=8;
const MAX_ATTEMPTS=3;
const headers={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Vary":"Authorization"};
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function json(status:number,body:Record<string,unknown>){return new Response(JSON.stringify(body),{status,headers});}
function text(v:unknown,max:number){return typeof v==="string"&&v.trim().length>0&&v.length<=max?v.trim():null;}
async function fp(token:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function caller(req:Request,admin:ReturnType<typeof createClient>){const verified=await verifyCaller(req,{supabaseUrl:URL,publishableKey:ANON,admin},["SYSTEM_ADMIN","CASE_STAFF","CONTENT_EDITOR"]);return verified.userId;}
async function credential(admin:ReturnType<typeof createClient>){const env=Deno.env.get("GOOGLE_SERVICE_ACCOUNT_JSON")??"";if(env)return JSON.parse(env);const {data,error}=await admin.rpc("get_firebase_fcm_service_account");if(error||typeof data!=="string"||!data.trim())throw new Error("FCM_CREDENTIALS_UNAVAILABLE");return JSON.parse(data);}
async function accessToken(admin:ReturnType<typeof createClient>){const creds=await credential(admin);const auth=new GoogleAuth({credentials:creds,scopes:["https://www.googleapis.com/auth/firebase.messaging"]});const c=await auth.getClient();const t=await c.getAccessToken();if(!t.token)throw new Error("FCM_CREDENTIALS_UNAVAILABLE");return {token:t.token,project:PROJECT||creds.project_id};}
function classify(status:number,body:any){const code=body?.error?.details?.find?.((x:any)=>x?.errorCode)?.errorCode??body?.error?.status??`HTTP_${status}`;const stale=status===404||status===410||code==="UNREGISTERED";const retry=status===429||status>=500||code==="UNAVAILABLE"||code==="INTERNAL";return {code:String(code),stale,retry};}
async function sendOne(admin:ReturnType<typeof createClient>,bearer:string,project:string,sourceId:string,device:any,title:string,body:string,payload:Record<string,string>){const fingerprint=await fp(device.fcm_token);const {data:existing}=await admin.from("notification_delivery_attempts").select("id,state,attempt_count,next_retry_at").eq("source_type","NOTIFICATION_EVENT").eq("source_id",sourceId).eq("token_fingerprint",fingerprint).maybeSingle();if(existing?.state==="ACCEPTED"||existing?.state==="PERMANENT_FAILURE")return existing.state;
 const {data:attempt,error:ae}=await admin.from("notification_delivery_attempts").upsert({source_type:"NOTIFICATION_EVENT",source_id:sourceId,device_registration_id:device.id,token_fingerprint:fingerprint,state:"PENDING"},{onConflict:"source_type,source_id,token_fingerprint"}).select("id,attempt_count").single();if(ae||!attempt)throw new Error("ATTEMPT_PERSISTENCE_FAILED");
 let lastStatus=0,lastCode="UNKNOWN";
 for(let i=0;i<MAX_ATTEMPTS;i++){const r=await fetch(`https://fcm.googleapis.com/v1/projects/${project}/messages:send`,{method:"POST",headers:{Authorization:`Bearer ${bearer}`,"Content-Type":"application/json"},body:JSON.stringify({message:{token:device.fcm_token,notification:{title,body},data:payload,android:{priority:"HIGH"}}})});if(r.ok){await admin.from("notification_delivery_attempts").update({state:"ACCEPTED",attempt_count:(attempt.attempt_count??0)+i+1,last_http_status:r.status,last_error_code:null,accepted_at:new Date().toISOString(),next_retry_at:null}).eq("id",attempt.id);return "ACCEPTED";}let rb:any={};try{rb=await r.json();}catch{}const c=classify(r.status,rb);lastStatus=r.status;lastCode=c.code;if(c.stale){await admin.from("device_registrations").delete().eq("id",device.id);await admin.from("notification_delivery_attempts").update({state:"PERMANENT_FAILURE",attempt_count:(attempt.attempt_count??0)+i+1,last_http_status:r.status,last_error_code:c.code,permanently_failed_at:new Date().toISOString(),next_retry_at:null}).eq("id",attempt.id);return "PERMANENT_FAILURE";}if(!c.retry){await admin.from("notification_delivery_attempts").update({state:"PERMANENT_FAILURE",attempt_count:(attempt.attempt_count??0)+i+1,last_http_status:r.status,last_error_code:c.code,permanently_failed_at:new Date().toISOString(),next_retry_at:null}).eq("id",attempt.id);return "PERMANENT_FAILURE";}if(i<MAX_ATTEMPTS-1)await sleep(250*Math.pow(2,i)+Math.floor(Math.random()*150));}
 const next=new Date(Date.now()+5*60_000).toISOString();await admin.from("notification_delivery_attempts").update({state:"RETRY_PENDING",attempt_count:(attempt.attempt_count??0)+MAX_ATTEMPTS,last_http_status:lastStatus,last_error_code:lastCode,next_retry_at:next}).eq("id",attempt.id);return "RETRY_PENDING";}
async function pool<T,R>(items:T[],fn:(x:T)=>Promise<R>){const out:R[]=[];let cursor=0;const workers=Array.from({length:Math.min(MAX_CONCURRENCY,items.length)},async()=>{while(cursor<items.length){const i=cursor++;out[i]=await fn(items[i]);}});await Promise.all(workers);return out;}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json(405,{error:"POST is required."});if(!URL||!ANON||!SERVICE)return json(503,{error:"Server configuration is incomplete."});const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});let actor:string|null=null;try{actor=await caller(req,admin);await enforceRateLimit(admin,"fcm_dispatch",actor,10,60);const input=await readJsonObject(req,16_384);const recipient=isUuid(input.recipientId)?input.recipientId:null,title=text(input.title,120),body=text(input.body,600),idem=text(input.idempotencyKey,128);if(!recipient||!title||!body)return json(400,{error:"recipientId, title, and body are required."});const entries=typeof input.payload==="object"&&input.payload!==null&&!Array.isArray(input.payload)?Object.entries(input.payload as Record<string,unknown>).slice(0,32):[];const payload=Object.fromEntries(entries.filter(([k,v])=>typeof v==="string"&&k.length<=64&&(v as string).length<=1024)) as Record<string,string>;if(idem)payload.idempotency_key=idem;
 let event:any=null;if(idem){const q=await admin.from("notification_events").select("id,delivered_at").eq("recipient_id",recipient).eq("notification_type","FCM").contains("payload",{idempotency_key:idem}).order("created_at",{ascending:false}).limit(1).maybeSingle();event=q.data;}
 if(!event){const ins=await admin.from("notification_events").insert({recipient_id:recipient,notification_type:"FCM",title,body,payload}).select("id,delivered_at").single();if(ins.error||!ins.data)throw new Error("EVENT_PERSISTENCE_FAILED");event=ins.data;}
 const devices=await admin.from("device_registrations").select("id,fcm_token").eq("user_id",recipient).limit(100);if(devices.error)throw new Error("DEVICE_LOOKUP_FAILED");if((devices.data??[]).length===0){await writeAudit(admin,{actorId:actor,eventType:"FCM_NOTIFICATION_DISPATCHED",result:"ALLOWED",entityType:"NOTIFICATION_EVENT",entityId:event.id,metadata:{recipientId:recipient,eligibleDevices:0}});return json(200,{notificationEventId:event.id,accepted:0,retryPending:0,permanentFailures:0});}const auth=await accessToken(admin);const results=await pool(devices.data??[],d=>sendOne(admin,auth.token,auth.project,event.id,d,title,body,payload));const accepted=results.filter(x=>x==="ACCEPTED").length,retryPending=results.filter(x=>x==="RETRY_PENDING").length,permanentFailures=results.filter(x=>x==="PERMANENT_FAILURE").length;if(accepted>0)await admin.from("notification_events").update({delivered_at:new Date().toISOString()}).eq("id",event.id);await writeAudit(admin,{actorId:actor,eventType:"FCM_NOTIFICATION_DISPATCHED",result:"ALLOWED",entityType:"NOTIFICATION_EVENT",entityId:event.id,metadata:{recipientId:recipient,eligibleDevices:results.length,accepted,retryPending,permanentFailures}});return json(200,{notificationEventId:event.id,eligibleDevices:results.length,accepted,retryPending,permanentFailures});}catch(e){const code=e instanceof Error?e.message:"UNKNOWN";await writeAudit(admin,{actorId:actor,eventType:"FCM_NOTIFICATION_DISPATCH_DENIED",result:code==="AUTH_REQUIRED"||code==="ROLE_REQUIRED"||code==="RATE_LIMITED"?"DENIED":"FAILED",metadata:{code}});return json(code==="AUTH_REQUIRED"?401:code==="ROLE_REQUIRED"?403:code==="RATE_LIMITED"?429:code==="INVALID_REQUEST"?400:code==="FCM_CREDENTIALS_UNAVAILABLE"?503:500,{error:code==="AUTH_REQUIRED"?"Sign in before dispatching notifications.":code==="ROLE_REQUIRED"?"This account is not authorised to dispatch notifications.":code==="RATE_LIMITED"?"Too many dispatch requests. Try again shortly.":code==="INVALID_REQUEST"?"The notification request is invalid.":"Notification delivery could not be completed."});}});
