android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
kotlin.daemon.jvmargs=-Xmx1536m
kotlin.code.style=official
supabase.production.url=https://pbzzfzfgwzwdstvnwzqu.supabase.co
supabase.production.publishableKey=sb_publishable_VKE5NH3l629RriDAlQVomg_NluPswET
