-- Reconstructed from read-only production catalog metadata on 2026-08-25.
-- This core layer contains structural tables and verified RLS policies only. It contains no
-- production data, credentials, scheduled jobs or synthetic release data.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  avatar_url text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.device_registrations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  fcm_token text not null unique,
  platform text not null default 'android' check (platform = 'android'),
  app_version text,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.notification_events (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references auth.users(id) on delete cascade,
  notification_type text not null,
  title text not null,
  body text not null,
  payload jsonb not null default '{}'::jsonb,
  delivered_at timestamptz,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id),
  event_type text not null,
  entity_type text not null,
  entity_id uuid,
  result text not null,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  source text not null default 'supabase'
);

create table if not exists public.directory_projects (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{2,120}$'),
  title text not null check (char_length(title) between 3 and 180),
  summary text not null check (char_length(summary) between 3 and 500),
  details text,
  sector text not null,
  project_status text not null check (project_status in ('PIPELINE', 'BUDGETED', 'SCHEDULED', 'ACTIVE_PLANNING', 'ONGOING', 'LAST_CONFIRMED', 'COMPLETED', 'ARCHIVED')),
  budget_amount numeric check (budget_amount is null or budget_amount >= 0),
  budget_currency char(3) not null default 'ZAR',
  source_url text,
  source_as_of date,
  visibility text not null default 'PUBLISHED' check (visibility in ('PUBLISHED', 'ARCHIVED')),
  display_order integer not null default 0,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.directory_centres (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{2,120}$'),
  name text not null check (char_length(name) between 3 and 180),
  summary text not null check (char_length(summary) between 3 and 500),
  category text not null,
  address text,
  locality text,
  phone text,
  email text,
  opening_hours text,
  directions_url text,
  visibility text not null default 'PUBLISHED' check (visibility in ('PUBLISHED', 'ARCHIVED')),
  display_order integer not null default 0,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.directory_opportunities (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{2,120}$'),
  title text not null check (char_length(title) between 3 and 180),
  summary text not null check (char_length(summary) between 3 and 500),
  opportunity_type text not null check (opportunity_type in ('JOB', 'LEARNERSHIP', 'BURSARY', 'TENDER', 'BUSINESS_SUPPORT', 'VOLUNTEER')),
  organisation text,
  locality text,
  closing_at timestamptz,
  application_url text,
  contact_email text,
  visibility text not null default 'PUBLISHED' check (visibility in ('PUBLISHED', 'ARCHIVED')),
  display_order integer not null default 0,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_media (
  id uuid primary key default gen_random_uuid(),
  target_type text not null check (target_type in ('PROJECT', 'CENTRE', 'OPPORTUNITY', 'NOTICE', 'ALERT')),
  target_id uuid not null,
  storage_path text not null unique,
  media_kind text not null check (media_kind in ('IMAGE', 'VIDEO')),
  mime_type text not null check (mime_type in ('image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/webm')),
  byte_size bigint not null,
  width integer check (width is null or width > 0),
  height integer check (height is null or height > 0),
  duration_seconds integer check (duration_seconds is null or duration_seconds between 1 and 180),
  position smallint not null check (position between 1 and 10),
  caption text check (caption is null or char_length(trim(caption)) between 1 and 500),
  uploaded_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id)
);

alter table public.profiles enable row level security;
alter table public.device_registrations enable row level security;
alter table public.notification_events enable row level security;
alter table public.audit_events enable row level security;
alter table public.directory_projects enable row level security;
alter table public.directory_centres enable row level security;
alter table public.directory_opportunities enable row level security;
alter table public.content_media enable row level security;

revoke all on public.profiles, public.device_registrations, public.notification_events,
  public.audit_events, public.directory_projects, public.directory_centres,
  public.directory_opportunities, public.content_media from anon, authenticated;

grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.device_registrations to authenticated;
grant select, update on public.notification_events to authenticated;
grant select on public.audit_events to authenticated;
grant select on public.directory_projects, public.directory_centres, public.directory_opportunities to anon, authenticated;
grant insert, update, delete on public.directory_projects, public.directory_centres, public.directory_opportunities to authenticated;

create index if not exists notification_events_recipient_created_idx on public.notification_events(recipient_id, created_at desc);
create index if not exists audit_events_occurred_idx on public.audit_events(occurred_at desc);
create index if not exists directory_projects_visibility_order_idx on public.directory_projects(visibility, display_order, created_at desc);
create index if not exists directory_centres_visibility_order_idx on public.directory_centres(visibility, display_order, created_at desc);
create index if not exists directory_opportunities_visibility_order_idx on public.directory_opportunities(visibility, display_order, closing_at nulls last);

create policy profiles_select_self_or_admin on public.profiles
  for select to authenticated
  using ((select auth.uid()) = id or private.has_role('SYSTEM_ADMIN'::public.app_role));
create policy profiles_update_self on public.profiles
  for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy device_registrations_select_own on public.device_registrations
  for select to authenticated using (user_id = (select auth.uid()));
create policy device_registrations_insert_own on public.device_registrations
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy device_registrations_update_own on public.device_registrations
  for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy device_registrations_delete_own on public.device_registrations
  for delete to authenticated using (user_id = (select auth.uid()));

create policy notification_events_select_own on public.notification_events
  for select to authenticated using (recipient_id = (select auth.uid()));
create policy notification_events_update_own on public.notification_events
  for update to authenticated using (recipient_id = (select auth.uid())) with check (recipient_id = (select auth.uid()));

create policy audit_events_select_admin on public.audit_events
  for select to authenticated using (private.has_role('SYSTEM_ADMIN'::public.app_role));

create policy directory_projects_public_read on public.directory_projects
  for select to anon, authenticated using (visibility = 'PUBLISHED');
create policy directory_projects_manage_editor_or_admin on public.directory_projects
  for all to authenticated
  using (private.has_any_role(array['CONTENT_EDITOR', 'SYSTEM_ADMIN']::public.app_role[]))
  with check (private.has_any_role(array['CONTENT_EDITOR', 'SYSTEM_ADMIN']::public.app_role[]));

create policy directory_centres_public_read on public.directory_centres
  for select to anon, authenticated using (visibility = 'PUBLISHED');
create policy directory_centres_manage_editor_or_admin on public.directory_centres
  for all to authenticated
  using (private.has_any_role(array['CONTENT_EDITOR', 'SYSTEM_ADMIN']::public.app_role[]))
  with check (private.has_any_role(array['CONTENT_EDITOR', 'SYSTEM_ADMIN']::public.app_role[]));

create policy directory_opportunities_public_read on public.directory_opportunities
  for select to anon, authenticated using (visibility = 'PUBLISHED');
create policy directory_opportunities_manage_editor_or_admin on public.directory_opportunities
  for all to authenticated
  using (private.has_any_role(array['CONTENT_EDITOR', 'SYSTEM_ADMIN']::public.app_role[]))
  with check (private.has_any_role(array['CONTENT_EDITOR', 'SYSTEM_ADMIN']::public.app_role[]));

-- Content-media policies are deliberately added only after their dependent visibility and
-- target-management helpers are reconstructed. Until then RLS denies all direct client access.
