import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { verifySchedulerCaller, writeAudit } from "../_shared/auth.ts";

const H={"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-rtc-alert-dispatch-secret","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const SCOPE="https://www.googleapis.com/auth/firebase.messaging";
const MAX_CONCURRENCY=8, MAX_ATTEMPTS=3;
type SA={project_id:string;client_email:string;private_key:string;token_uri?:string};
type Alert={id:string;category:string;title:string;summary:string;expires_at:string;intended_recipient_count:number};
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function json(status:number,body:Record<string,unknown>){return new Response(JSON.stringify(body),{status,headers:H});}
function b64(value:ArrayBuffer|string){const bytes=typeof value==="string"?new TextEncoder().encode(value):new Uint8Array(value);let binary="";bytes.forEach(b=>binary+=String.fromCharCode(b));return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function pem(p:string){const x=p.replace("-----BEGIN PRIVATE KEY-----","").replace("-----END PRIVATE KEY-----","").replace(/\s/g,"");const bin=atob(x),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes.buffer;}
async function accessToken(a:SA){const now=Math.floor(Date.now()/1000),uri=a.token_uri??"https://oauth2.googleapis.com/token",head=b64(JSON.stringify({alg:"RS256",typ:"JWT"})),claim=b64(JSON.stringify({iss:a.client_email,scope:SCOPE,aud:uri,iat:now,exp:now+3600})),unsigned=`${head}.${claim}`,key=await crypto.subtle.importKey("pkcs8",pem(a.private_key),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]),sig=await crypto.subtle.sign({name:"RSASSA-PKCS1-v1_5"},key,new TextEncoder().encode(unsigned)),r=await fetch(uri,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:`${unsigned}.${b64(sig)}`})});if(!r.ok)throw new Error("FCM_ACCESS_TOKEN_FAILED");const o=await r.json() as {access_token?:string};if(!o.access_token)throw new Error("FCM_ACCESS_TOKEN_FAILED");return o.access_token;}
async function fp(token:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("");}
function classify(status:number,b:any){const code=b?.error?.details?.find?.((x:any)=>x?.errorCode)?.errorCode??b?.error?.status??`HTTP_${status}`;return {code:String(code),stale:status===404||status===410||code==="UNREGISTERED",retry:status===429||status>=500||code==="UNAVAILABLE"||code==="INTERNAL"};}
async function pool<T,R>(items:T[],fn:(x:T)=>Promise<R>){const out:R[]=[];let cursor=0;await Promise.all(Array.from({length:Math.min(MAX_CONCURRENCY,items.length)},async()=>{while(cursor<items.length){const i=cursor++;out[i]=await fn(items[i]);}}));return out;}
async function deliver(service:ReturnType<typeof createClient>,bearer:string,account:SA,alert:Alert,device:any){const fingerprint=await fp(device.fcm_token);const {data:existing}=await service.from("notification_delivery_attempts").select("id,state,attempt_count,next_retry_at").eq("source_type","COMMUNITY_ALERT").eq("source_id",alert.id).eq("token_fingerprint",fingerprint).maybeSingle();if(existing?.state==="ACCEPTED"||existing?.state==="PERMANENT_FAILURE")return existing.state;if(existing?.state==="RETRY_PENDING"&&existing.next_retry_at&&Date.parse(existing.next_retry_at)>Date.now())return "RETRY_PENDING";
 const {data:a,error}=await service.from("notification_delivery_attempts").upsert({source_type:"COMMUNITY_ALERT",source_id:alert.id,device_registration_id:device.id,token_fingerprint:fingerprint,state:"PENDING",next_retry_at:null},{onConflict:"source_type,source_id,token_fingerprint"}).select("id,attempt_count").single();if(error||!a)throw new Error("ATTEMPT_PERSISTENCE_FAILED");let hs=0,code="UNKNOWN";
 for(let i=0;i<MAX_ATTEMPTS;i++){const emergency=alert.category==="SAFETY_EMERGENCY",r=await fetch(`https://fcm.googleapis.com/v1/projects/${account.project_id}/messages:send`,{method:"POST",headers:{Authorization:`Bearer ${bearer}`,"Content-Type":"application/json"},body:JSON.stringify({message:{token:device.fcm_token,notification:{title:alert.title,body:alert.summary},data:{route:"community_alert",alert_id:alert.id,category:alert.category},android:{priority:emergency?"high":"normal",notification:{channel_id:emergency?"rtc_safety_alerts":"rtc_community_updates",notification_priority:emergency?"PRIORITY_HIGH":"PRIORITY_DEFAULT"}}}})});if(r.ok){await service.from("notification_delivery_attempts").update({state:"ACCEPTED",attempt_count:(a.attempt_count??0)+i+1,last_http_status:r.status,last_error_code:null,accepted_at:new Date().toISOString(),next_retry_at:null}).eq("id",a.id);return "ACCEPTED";}let body:any={};try{body=await r.json();}catch{}const c=classify(r.status,body);hs=r.status;code=c.code;if(c.stale){await service.from("device_registrations").delete().eq("id",device.id);await service.from("notification_delivery_attempts").update({state:"PERMANENT_FAILURE",attempt_count:(a.attempt_count??0)+i+1,last_http_status:hs,last_error_code:code,permanently_failed_at:new Date().toISOString(),next_retry_at:null}).eq("id",a.id);return "PERMANENT_FAILURE";}if(!c.retry){await service.from("notification_delivery_attempts").update({state:"PERMANENT_FAILURE",attempt_count:(a.attempt_count??0)+i+1,last_http_status:hs,last_error_code:code,permanently_failed_at:new Date().toISOString(),next_retry_at:null}).eq("id",a.id);return "PERMANENT_FAILURE";}if(i<MAX_ATTEMPTS-1)await sleep(250*Math.pow(2,i)+Math.floor(Math.random()*150));}
 await service.from("notification_delivery_attempts").update({state:"RETRY_PENDING",attempt_count:(a.attempt_count??0)+MAX_ATTEMPTS,last_http_status:hs,last_error_code:code,next_retry_at:new Date(Date.now()+5*60_000).toISOString()}).eq("id",a.id);return "RETRY_PENDING";}
Deno.serve(async(request)=>{if(request.method==="OPTIONS")return new Response("ok",{headers:H});if(request.method!=="POST")return json(405,{error:"POST is required."});const url=Deno.env.get("SUPABASE_URL")??"",serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??Deno.env.get("SUPABASE_SECRET_KEY")??"";if(!url||!serviceKey)return json(503,{error:"Alert delivery is not configured."});const service=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});try{await verifySchedulerCaller(request,service);}catch{await writeAudit(service,{actorId:null,eventType:"COMMUNITY_ALERT_DISPATCH_DENIED",result:"DENIED",metadata:{reason:"scheduler_secret"}});return json(401,{error:"Unauthorized alert-dispatch request."});}
 try{const claim=await service.rpc("claim_pending_community_alert_dispatch"),alert=(claim.data as Alert[]|null)?.[0];if(claim.error)throw new Error("ALERT_CLAIM_FAILED");if(!alert){await writeAudit(service,{actorId:null,eventType:"COMMUNITY_ALERT_DISPATCH_IDLE",result:"ALLOWED",metadata:{processed:0}});return json(200,{processed:0});}const ar=await service.from("community_alerts").select("created_by").eq("id",alert.id).single(),rec=await service.from("notification_events").select("recipient_id").eq("notification_type","COMMUNITY_ALERT").contains("payload",{alert_id:alert.id}).limit(10000);if(rec.error)throw new Error("RECIPIENT_LOOKUP_FAILED");const ids=[...new Set((rec.data??[]).map((r:any)=>r.recipient_id))],dev=ids.length===0?{data:[],error:null}:await service.from("device_registrations").select("id,fcm_token").in("user_id",ids).limit(10000);if(dev.error)throw new Error("DEVICE_LOOKUP_FAILED");const devices=[...new Map((dev.data??[]).map((d:any)=>[d.fcm_token,d])).values()];if(devices.length===0){await service.from("community_alerts").update({eligible_device_count:0,fcm_accepted_count:0,fcm_failed_count:0,dispatch_state:"NO_DEVICES",dispatched_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",alert.id);await writeAudit(service,{actorId:ar.data?.created_by??null,eventType:"COMMUNITY_ALERT_DISPATCHED",result:"ALLOWED",entityType:"COMMUNITY_ALERT",entityId:alert.id,metadata:{eligibleDevices:0}});return json(200,{processed:1,alertId:alert.id,dispatchState:"NO_DEVICES"});}
 const cred=await service.rpc("get_firebase_fcm_service_account");if(cred.error||typeof cred.data!=="string"||!cred.data.trim())throw new Error("FCM_CREDENTIAL_UNAVAILABLE");const account=JSON.parse(cred.data) as SA,bearer=await accessToken(account);await pool(devices,d=>deliver(service,bearer,account,alert,d));const states=await service.from("notification_delivery_attempts").select("state").eq("source_type","COMMUNITY_ALERT").eq("source_id",alert.id);if(states.error)throw new Error("ATTEMPT_SUMMARY_FAILED");const accepted=(states.data??[]).filter((x:any)=>x.state==="ACCEPTED").length,retry=(states.data??[]).filter((x:any)=>x.state==="RETRY_PENDING"||x.state==="PENDING").length,permanent=(states.data??[]).filter((x:any)=>x.state==="PERMANENT_FAILURE").length,finalState=retry>0?"PENDING":permanent===0?"COMPLETE":accepted>0?"PARTIAL":"FAILED";await service.from("community_alerts").update({eligible_device_count:devices.length,fcm_accepted_count:accepted,fcm_failed_count:permanent,dispatch_state:finalState,dispatched_at:retry===0?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",alert.id);await writeAudit(service,{actorId:ar.data?.created_by??null,eventType:"COMMUNITY_ALERT_DISPATCHED",result:"ALLOWED",entityType:"COMMUNITY_ALERT",entityId:alert.id,metadata:{intendedRecipients:alert.intended_recipient_count,eligibleDevices:devices.length,fcmAccepted:accepted,retryPending:retry,permanentFailures:permanent,dispatchState:finalState}});return json(200,{processed:1,alertId:alert.id,dispatchState:finalState,eligibleDevices:devices.length,accepted,retryPending:retry,permanentFailures:permanent});}catch(e){const code=e instanceof Error?e.message:"ALERT_DISPATCH_FAILED";await writeAudit(service,{actorId:null,eventType:"COMMUNITY_ALERT_DISPATCH_FAILED",result:"FAILED",metadata:{code}});return json(500,{error:"Alert delivery could not be completed."});}});
